# Site settings
title: I-CubeX PiShield 
url: "http://I-CubeX.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/PiShieldDocs"  # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Canada/Eastern
description: >
  One or more sentences introducing this blog.

# Your information
email: support@infusionsystems.com 
author: I-CubeX
avatar: "//avatars1.githubusercontent.com/u/10518183?v=3&s=200"
profile: One sentence introducing yourself.
#twitter_username: twitter_username
github_username: I-CubeX 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archive/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
